// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScheduleModule.Repositories.Entities;

public partial class Employee
{
    [Key]
    public Guid EmployeeId { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<RolesToEmployee> RolesToEmployees { get; set; } = new List<RolesToEmployee>();
}