// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ScheduleModule.Repositories.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ScheduleModule.Repositories.Entities
{
    public partial interface IScheduleContextProcedures
    {
        Task<List<spGetShiftsForWeekResult>> spGetShiftsForWeekAsync(DateOnly? FirstDateOfTheWeek, Guid? EmployeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
