// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScheduleModule.Repositories.Entities;

public partial class Role
{
    [Key]
    public Guid RoleId { get; set; }

    [Required]
    [StringLength(50)]
    public string RoleName { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RolesToEmployee> RolesToEmployees { get; set; } = new List<RolesToEmployee>();
}