// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScheduleModule.Repositories.Entities;

public partial class RolesToEmployee
{
    [Key]
    public Guid RolesToEmployeeId { get; set; }

    public Guid EmployeeId { get; set; }

    public Guid RoleId { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("RolesToEmployees")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("RolesToEmployees")]
    public virtual Role Role { get; set; }

    [InverseProperty("RolesToEmployee")]
    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();
}