// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ScheduleModule.Repositories.Entities;

public partial class ScheduleContext : DbContext
{
    public ScheduleContext(DbContextOptions<ScheduleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolesToEmployee> RolesToEmployees { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.Property(e => e.EmployeeId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.Property(e => e.RoleId).ValueGeneratedNever();
        });

        modelBuilder.Entity<RolesToEmployee>(entity =>
        {
            entity.Property(e => e.RolesToEmployeeId).ValueGeneratedNever();

            entity.HasOne(d => d.Employee).WithMany(p => p.RolesToEmployees)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolesToEmployees_Employees");

            entity.HasOne(d => d.Role).WithMany(p => p.RolesToEmployees)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolesToEmployees_Roles");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.Property(e => e.ShiftId).ValueGeneratedNever();

            entity.HasOne(d => d.RolesToEmployee).WithMany(p => p.Shifts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shifts_RolesToEmployees");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}