// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ScheduleModule.Repositories.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ScheduleModule.Repositories.Entities
{
    public partial class ScheduleContext
    {
        private IScheduleContextProcedures _procedures;

        public virtual IScheduleContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ScheduleContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IScheduleContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<spGetShiftsForWeekResult>().HasNoKey().ToView(null);
        }
    }

    public partial class ScheduleContextProcedures : IScheduleContextProcedures
    {
        private readonly ScheduleContext _context;

        public ScheduleContextProcedures(ScheduleContext context)
        {
            _context = context;
        }

        public virtual async Task<List<spGetShiftsForWeekResult>> spGetShiftsForWeekAsync(DateOnly? FirstDateOfTheWeek, Guid? EmployeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FirstDateOfTheWeek",
                    Value = FirstDateOfTheWeek ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "EmployeeId",
                    Value = EmployeeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetShiftsForWeekResult>("EXEC @returnValue = [dbo].[spGetShiftsForWeek] @FirstDateOfTheWeek, @EmployeeId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
