// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScheduleModule.Repositories.Entities;

public partial class Shift
{
    [Key]
    public Guid ShiftId { get; set; }

    public Guid RolesToEmployeeId { get; set; }

    public DateOnly? Date { get; set; }

    public TimeOnly StartHour { get; set; }

    public TimeOnly EndHour { get; set; }

    [ForeignKey("RolesToEmployeeId")]
    [InverseProperty("Shifts")]
    public virtual RolesToEmployee RolesToEmployee { get; set; }
}