// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScheduleModule.Repositories.Entities
{
    public partial class uspGetShiftsForWeekResult
    {
        public Guid EmployeeId { get; set; }
        public string FullName { get; set; }
        public DateOnly? Date { get; set; }
        public Guid ShiftId { get; set; }
        public string RoleName { get; set; }
        public TimeOnly StartHour { get; set; }
        public TimeOnly EndHour { get; set; }
    }
}
